-- MySQL Script generated by MySQL Workbench
-- Sun Nov  6 19:43:32 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema book-store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema book-store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `book-store` DEFAULT CHARACTER SET utf8 ;
USE `book-store` ;

-- -----------------------------------------------------
-- Table `book-store`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book-store`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(60) NULL,
  `name` VARCHAR(45) NULL,
  `phone` VARCHAR(15) NULL,
  `gender` INT NULL,
  `address` VARCHAR(255) NULL,
  `avatar` VARCHAR(255) NULL,
  `money` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book-store`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book-store`.`role` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book-store`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book-store`.`user_role` (
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `fk_user_has_role_role1_idx` (`role_id` ASC) VISIBLE,
  INDEX `fk_user_has_role_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_role_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `book-store`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `book-store`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book-store`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book-store`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book-store`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book-store`.`book` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  `translator` VARCHAR(45) NULL,
  `publishing_company` VARCHAR(45) NOT NULL,
  `num_page` INT NULL,
  `size` VARCHAR(45) NULL,
  `release_date` VARCHAR(45) NULL,
  `price` INT NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book-store`.`book_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book-store`.`book_category` (
  `book_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`book_id`, `category_id`),
  INDEX `fk_book_has_category_category1_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_book_has_category_book1_idx` (`book_id` ASC) VISIBLE,
  CONSTRAINT `fk_book_has_category_book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `book-store`.`book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_has_category_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `book-store`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book-store`.`invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book-store`.`invoice` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `export_date` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_invoice_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_invoice_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `book-store`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book-store`.`invoice_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book-store`.`invoice_detail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `invoice_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_invoice_detail_invoice1_idx` (`invoice_id` ASC) VISIBLE,
  INDEX `fk_invoice_detail_book1_idx` (`book_id` ASC) VISIBLE,
  CONSTRAINT `fk_invoice_detail_invoice1`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `book-store`.`invoice` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoice_detail_book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `book-store`.`book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book-store`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book-store`.`cart` (
  `user_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`user_id`, `book_id`),
  INDEX `fk_user_has_book_book1_idx` (`book_id` ASC) VISIBLE,
  INDEX `fk_user_has_book_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_book_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `book-store`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_book_book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `book-store`.`book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book-store`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book-store`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_comment_book1_idx` (`book_id` ASC) VISIBLE,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `book-store`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `book-store`.`book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
